export const PERMISSIONS = {
  // ======================
  // STUDENTS
  // ======================
  CREATE_STUDENT: "CREATE_STUDENT",
  UPDATE_STUDENT: "UPDATE_STUDENT",
  VIEW_STUDENT: "VIEW_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",
  GENERATE_STUDENT_REPORT: "GENERATE_STUDENT_REPORT",


  // ======================
  // TEACHERS
  // ======================
  CREATE_TEACHER: "CREATE_TEACHER",
  VIEW_TEACHER: "VIEW_TEACHER",
  UPDATE_TEACHER: "UPDATE_TEACHER",
  DELETE_TEACHER: "DELETE_TEACHER",
  GENERATE_TEACHER_REPORT: "GENERATE_TEACHER_REPORT",
  

  // ======================
  // CLASSES
  // ======================
  CREATE_CLASS: "CREATE_CLASS",
  UPDATE_CLASS: "UPDATE_CLASS",
  VIEW_CLASS: "VIEW_CLASS",
  DELETE_CLASS: "DELETE_CLASS",
  ADD_STUDENT_TO_CLASS: "ADD_STUDENT_TO_CLASS",
  REMOVE_STUDENT_FROM_CLASS: "REMOVE_STUDENT_FROM_CLASS",


  // ======================
  // SUBJECTS
  // ======================
  CREATE_SUBJECT: "CREATE_SUBJECT",
  UPDATE_SUBJECT: "UPDATE_SUBJECT",
  VIEW_SUBJECT: "VIEW_SUBJECT",
  DELETE_SUBJECT: "DELETE_SUBJECT",
  ASSIGN_SUBJECT_TO_TEACHER: "ASSIGN_SUBJECT_TO_TEACHER",
  REMOVE_SUBJECT_FROM_TEACHER: "REMOVE_SUBJECT_FROM_TEACHER",


  // ======================
  // ATTENDANCE (IMPORTANT)
  // ======================
  CREATE_ATTENDANCE_SESSION: "CREATE_ATTENDANCE_SESSION",
  MARK_ATTENDANCE: "MARK_ATTENDANCE",
  VIEW_ATTENDANCE: "VIEW_ATTENDANCE",
  UPDATE_ATTENDANCE: "UPDATE_ATTENDANCE",
  DELETE_ATTENDANCE: "DELETE_ATTENDANCE",
  GENERATE_ATTENDANCE_REPORT: "GENERATE_ATTENDANCE_REPORT",

  // ======================
  // RESULTS / ACADEMICS
  // ======================
  CREATE_ASSESSMENT: "CREATE_ASSESSMENT",
  UPDATE_ASSESSMENT: "UPDATE_ASSESSMENT",
  DELETE_ASSESSMENT: "DELETE_ASSESSMENT",
  VIEW_ASSESSMENT: "VIEW_ASSESSMENT",
  ENTER_RESULTS: "ENTER_RESULTS",
  VIEW_RESULTS: "VIEW_RESULTS",
  GENERATE_REPORT_CARD: "GENERATE_REPORT_CARD",


  // ======================
  // FEES
  // ======================
  CREATE_FEE_STRUCTURE: "CREATE_FEE_STRUCTURE",
  UPDATE_FEE_STRUCTURE: "UPDATE_FEE_STRUCTURE",
  DELETE_FEE_STRUCTURE: "DELETE_FEE_STRUCTURE",
  VIEW_FEES: "VIEW_FEES",
  RECORD_PAYMENT: "RECORD_PAYMENT",
  GENERATE_FEE_RECEIPT: "GENERATE_FEE_RECEIPT",

  // ======================
  // INVOICES
  // ======================
  CREATE_INVOICE: "CREATE_INVOICE",
  VIEW_INVOICE: "VIEW_INVOICE",
  UPDATE_INVOICE: "UPDATE_INVOICE",
  DELETE_INVOICE: "DELETE_INVOICE",
  GENERATE_INVOICE: "GENERATE_INVOICE",

  // ======================
  // COMMUNICATION
  // ======================
  CREATE_ANNOUNCEMENT: "CREATE_ANNOUNCEMENT",
  VIEW_ANNOUNCEMENT: "VIEW_ANNOUNCEMENT",
  SEND_MESSAGE: "SEND_MESSAGE",
  VIEW_MESSAGES: "VIEW_MESSAGES",
  CREATE_NOTIFICATION: "CREATE_NOTIFICATION",
  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",

  // ======================
  // ONBOARDING
  // ======================
  ONBOARD_STUDENT: "ONBOARD_STUDENT",
  ONBOARD_TEACHER: "ONBOARD_TEACHER",
  ONBOARD_PARENT: "ONBOARD_PARENT",
  UPDATE_ONBOARDING: "UPDATE_ONBOARDING",
  DELETE_ONBOARDING: "DELETE_ONBOARDING",
  GENERATE_ONBOARDING_REPORT: "GENERATE_ONBOARDING_REPORT",

  // ======================
  // SCHOOL ADMIN
  // ======================
  MANAGE_SCHOOL: "MANAGE_SCHOOL",
  MANAGE_USERS: "MANAGE_USERS",
  UPDATE_SCHOOL: "UPDATE_SCHOOL",
  DELETE_SCHOOL: "DELETE_SCHOOL",
  GENERATE_SCHOOL_REPORT: "GENERATE_SCHOOL_REPORT",
} as const;