import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  ADMIN: Object.values(PERMISSIONS),

  TEACHER: [
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.CREATE_ATTENDANCE_SESSION,
    PERMISSIONS.VIEW_STUDENT,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.VIEW_RESULTS,
  ],

  STAFF: [
    PERMISSIONS.VIEW_STUDENT,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.VIEW_INVOICE,
  ],

  PARENT: [
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.VIEW_INVOICE,
  ],

  STUDENT: [
    PERMISSIONS.VIEW_RESULTS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_INVOICE,
  ],
};