export const AuditActions = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  ACCESS_REQUEST_CREATED: "ACCESS_REQUEST_CREATED",
  ACCESS_REQUEST_APPROVED: "ACCESS_REQUEST_APPROVED",
  ACCESS_REQUEST_REJECTED: "ACCESS_REQUEST_REJECTED",

  STUDENT_CREATED: "STUDENT_CREATED",
  TEACHER_CREATED: "TEACHER_CREATED",

  FEE_PAYMENT_CREATED: "FEE_PAYMENT_CREATED",
};